package sg.edu.nus.imovin.GreenDAO;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOG_FUNC_CLICK".
 */
@Entity
public class LogFuncClick {

    @Id(autoincrement = true)
    private Long id;
    private int RecordDateYear;
    private int RecordDateMonth;
    private int RecordDateDay;
    private int UpdateFlag;
    private int HomeCount;
    private int ChallengeCount;
    private int LibraryCount;
    private int SocialCount;
    private int ForumCount;
    private int MonitorCount;
    private int GoalCount;

    @Generated
    public LogFuncClick() {
    }

    public LogFuncClick(Long id) {
        this.id = id;
    }

    @Generated
    public LogFuncClick(Long id, int RecordDateYear, int RecordDateMonth, int RecordDateDay, int UpdateFlag, int HomeCount, int ChallengeCount, int LibraryCount, int SocialCount, int ForumCount, int MonitorCount, int GoalCount) {
        this.id = id;
        this.RecordDateYear = RecordDateYear;
        this.RecordDateMonth = RecordDateMonth;
        this.RecordDateDay = RecordDateDay;
        this.UpdateFlag = UpdateFlag;
        this.HomeCount = HomeCount;
        this.ChallengeCount = ChallengeCount;
        this.LibraryCount = LibraryCount;
        this.SocialCount = SocialCount;
        this.ForumCount = ForumCount;
        this.MonitorCount = MonitorCount;
        this.GoalCount = GoalCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRecordDateYear() {
        return RecordDateYear;
    }

    public void setRecordDateYear(int RecordDateYear) {
        this.RecordDateYear = RecordDateYear;
    }

    public int getRecordDateMonth() {
        return RecordDateMonth;
    }

    public void setRecordDateMonth(int RecordDateMonth) {
        this.RecordDateMonth = RecordDateMonth;
    }

    public int getRecordDateDay() {
        return RecordDateDay;
    }

    public void setRecordDateDay(int RecordDateDay) {
        this.RecordDateDay = RecordDateDay;
    }

    public int getUpdateFlag() {
        return UpdateFlag;
    }

    public void setUpdateFlag(int UpdateFlag) {
        this.UpdateFlag = UpdateFlag;
    }

    public int getHomeCount() {
        return HomeCount;
    }

    public void setHomeCount(int HomeCount) {
        this.HomeCount = HomeCount;
    }

    public int getChallengeCount() {
        return ChallengeCount;
    }

    public void setChallengeCount(int ChallengeCount) {
        this.ChallengeCount = ChallengeCount;
    }

    public int getLibraryCount() {
        return LibraryCount;
    }

    public void setLibraryCount(int LibraryCount) {
        this.LibraryCount = LibraryCount;
    }

    public int getSocialCount() {
        return SocialCount;
    }

    public void setSocialCount(int SocialCount) {
        this.SocialCount = SocialCount;
    }

    public int getForumCount() {
        return ForumCount;
    }

    public void setForumCount(int ForumCount) {
        this.ForumCount = ForumCount;
    }

    public int getMonitorCount() {
        return MonitorCount;
    }

    public void setMonitorCount(int MonitorCount) {
        this.MonitorCount = MonitorCount;
    }

    public int getGoalCount() {
        return GoalCount;
    }

    public void setGoalCount(int GoalCount) {
        this.GoalCount = GoalCount;
    }

}
